SHELL=bash

include .make/Makefile

vignettes/startup-intro.md: OVERVIEW.md vignettes/incl/clean.css
	sed -E -i '/^(<!-- DO NOT EDIT THIS FILE|!\[|#+[[:space:]])/,$$d' $@
	echo "<!-- DO NOT EDIT THIS FILE! Edit 'OVERVIEW.md' instead and then rebuild this file with 'make vigs' -->" >> $@
	cat $< >> $@

vigs: vignettes/startup-intro.md

pkgdown: .pkgdown

.pkgdown:
	rsync --archive --delete --exclude="$@" --exclude=".git*" . "$@"
# Turn *.md files into *.Rmd
	for ff in "$@"/vignettes/*.md; do \
	  echo "Vignette: $$ff"; \
	  make "$${ff/.md/.Rmd}"; \
	done
	Rscript -e "pkgdown::build_site('$@', preview = FALSE)"

.pkgdown/vignettes/%.Rmd:
	ff="$@"; \
	ss="$${ff/.Rmd/.md}"; \
	title=$$(sed -n '/.*%\\VignetteIndexEntry{.*}/p' "$$ss" | sed -E 's/.*\{(.*)\}/\1/'); \
	echo "title=\"$$title\""; \
	author=$$(sed -n '/.*%\\VignetteAuthor{.*}/p' "$$ss" | sed -E 's/.*\{(.*)\}/\1/'); \
	echo "author=\"$$author\""; \
	{ \
	   echo "---"; \
	   echo "title: \"$$title\""; \
	   echo "author: \"$$author\""; \
	   echo "---"; \
	   cat "$$ss"; \
	} >> "$$ff"
	rm "$$ss"

docs: .pkgdown
	rsync --archive --delete "$</$@" .
	for ff in "$@"/articles/*.html; do \
	  tt=vignettes/$$(basename "$$ff"); \
	  dd="$${tt/.html/.md}"; \
	  ss="$${dd/.md/.Rmd}"; \
	  echo "tt=$$tt"; \
	  echo "dd=$$dd"; \
	  echo "ss=$$ss"; \
	  echo sed -i "s|$$ss|$$dd|g" "$$ff"; \
	  sed -i "s|$$ss|$$dd|g" "$$ff"; \
	  sed -i "s|$$ss|$$dd|g" "$$ff"; \
	done

FORCE:
